### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by owenrjohnson**
We should really start using this again like theres absolutely no reason not to especially if we leave code on people's personal laptops

### CODE REVIEW

**Comment by Danny-Dunn** [comment]
Are we not going to use classes? A 700 line code file is a bit ridiculous.

**Comment by Danny-Dunn** [comment]
Also we need to use classes so that multiple people can efficiently work on the code. It's way too easy to create conflicting changes with a single code file.

**Comment by owenrjohnson** [comment]
I don't know how to use github yet lmao. We can tweak it later, I just
thought something was better than nothing

**Comment by Danny-Dunn** [comment]
Yeah it's a good start we can restructure today.

**Comment by owenrjohnson** [comment]
I won’t be there today but I’m sure it wont be too difficult. Also Matt’s not going to be there either if i remember correctly so depending on if ben and szander are there or not we can save it for tomorrow so you can get everyone up to speed on how it works.

**Comment by Danny-Dunn** [comment]
Yeah that makes more sense. I'll see if I'm in tmr.

**Pull request merged**
